- README.md
Either DEIS_REGISTRY or DEV_REGISTRY should be set before launching the
command `make build`.
> docs(readme): Add note on registry vars on make build

- Makefile
This reverts commit 8faef2cc3c05ebd85023f12a8085c4c6cef0d539.
This experiment failed pretty quickly.  Although I _could_ get stable builds from it, I started running into numerous other issues in the alpine-based dev environment.  afaict, there were some pretty significant problems with volumes mounted from the host (i.e. the project's working directory).  I could make changes to files on my Mac and then back in the container, some containerized programs (it would seem just ones that open files for write, such as vi) would _see_ the changes, while others such as cat and grep would not.  To me this smells like some sort of file system issue and it's something we can't afford the time to troubleshoot right now when a working dev environment already exists.
> chore(Makefile): switch OFF of alpine-based dev environment

- Makefile
- includes.mk
This PR adds a variety of make targets as placeholders for containerized test processes.  The one that is fully implemented is the style checks.
After this PR, `make test`, actually works, which means I can also get going on integrating this with CI.
> feat(Makefile): add make targets for testing

- Makefile
This allows the right host dir to be mounted into the containerized development environment even when the make target is executed from another directory-- e.g. `make -C .. push` during execution of `_scripts/deploy.sh`.
> fix(ci): drive volume mounts of CURDIR instead of PWD

- model/model.go
- nginx/config.go
Attn: @arschles 
While adding support for the builder, I stumbled across the edge case of missing annotations.  In the case of builder, I can roll with defaults.  Awareness of this edge case and my technique for handling it did lead to a more general refactor of how this chunk of code builds the model, that and a liberal sprinkling of new comments to explain what the hell I'm doing.  Please forgive that slight scope creep.
~~If you want to use this with builder (as installed by helm), there's only one thing you actually need to do-- you need to move the builder's service into the "deis" namespace.  Moving all the deis components into the "deis" namespace has been a previous topic of discussion and has been something we'll "get around to at some point."  I guess it's time?  (It sort of …
> feat(router): support stream for builder

- manifests/deis-router-rc.yaml
- manifests/examples.yaml
- model/model.go
Before this PR, routable services could be annotated with a list of domains, but that meant if someone wanted to change their "platform domain," every routable service would require its annotations to be updated-- no bueno.
This PR allows the platform domain (e.g. example.com) to be configured at the _router_ level and any "domains" defined on a routable application that do not contain any periods will be assumed to be subdomains of the platform domain when the router builds its configuration model.
> feat(router): make platform domain configurable

- README.md
This is a rough cut of instructions for how to configure the router via annotations.  Right now this is mainly for @helgi's benefit, especially WRT to the router configuration options he can make workflow add/manage on each application's k8s services.
More options will be added to this table as they are implemented.
> doc(router): document config options

- manifests/deis-router-rc.yaml
- model/model.go
This is insipired by deis/charts#23
For consistency, I also renamed the env variable to `POD_NAMESPACE`
> chore(router): use downward api to set POD_NAMESPACE env var

- nginx/config.go
This PR continues the march toward feature parity.  ~~WIP, because it will need a rebase and doc updates after #27 is merged.~~
Note the "basic settings" are inherited directly from the v1.x router.
> feat(router): configure "basic settings"

- README.md
- model/model.go
- nginx/config.go
This is the first of many PRs that will incrementally bring the router into feature parity with the v1.x router.
~~Note I have designated this as a WIP because it will require rebase and further doc modifications after #27 is merged.~~
> feat(router): support configuration of worker procs and connections

- README.md
- model/model.go
- nginx/config.go
Alternative implementation of #35.  Ping @helgi: this drops the extra `useGzip` config option in favor of operators nulling out the `gzipConfig` if they want to disable it entirely.  lmk what you think.
> feat(router): add gzip support (option 2)

- nginx/config.go
This is probably unnecessary, but it makes us more similar to v1.x's router.
> chore(router): move pid to be consistent with v1.x

- nginx/config.go
Fill out the remaining proxy settings for an app, minus anything having to do with SSL, enforcing HTTPS, etc.
> chore(router): inherit more app proxy settings from v1.x

- manifests/deis-router-rc.yaml
- nginx/config.go
It would actually be nice to proxy the router healthchecks through to the kube-proxy-- which must also be functioning for the router to successfully route traffic, but if we want to run in any k8s cluster, there's really no guarantee that k8s components are configured to respond to health checks, as that is configurable.
> feat(router): add router healthchecks

- manifests/deis-router-rc.yaml
- model/model.go
When a domain is not present in the routerConfig, we revert back to
a wildcard platform domain so users can make the platform domain
anything they wish.
Once this is merged, we can then remove the `domain` argument from the deis chart and move the router configuration in the docs somewhere else. This makes us compatible with the v1 router's routing behaviour.
> feat(router): make platform domain optional

- glide.lock
- glide.yaml
- model/model.go
- nginx/config.go
This partly undoes #67.  It retains the functionality that was introduced there, but achieves it without the possibility of putting nginx-specific regex patterns in the model.  By not polluting the model we increase the ease with which we could swap nginx for something else in the future.
> router(model): Clean model WRT to nginx-specific domain configuration

- Makefile
- README.md
These are minor doc updates to reflect that the registry _should_ end with a trailing slash whilst the image prefix should not.  That was changed a while ago and docs were not updated accordingly at that time.
> doc(router): Update docs for accuracy

- Makefile
- README.md
- manifests/deis-router-rc.yaml
- manifests/examples.yaml
- model/model.go
- utils/modeler/errors.go
- utils/modeler/modeler.go
- utils/modeler/modeler_test.go
Fixes #63 
~~This is WIP.  There are more commits to come as part of this PR.~~
> Do not use JSON for router configuration

- nginx/config.go
- rootfs/bin/build
This PR removes the `vhost_traffic_status_zone` directive.  That is part of the "virtual host traffic status module," which was only ever used for the sake of a status page that's been consciously omitted from v2 for security reasons.
With that directive gone, there are a total of 4 unused Nginx modules that this PR also removes.
> Remove unused config and modules

- README.md
- model/model.go
- nginx/config.go
This is a follow up to #75 to add SSL support for "custom domains".
This essentially generalizes some of what was done in #75 to allow certificates born by k8s secrets to be obtained and used to secure virtual hosts for any fully-qualified domain names associated with a routable service.
> feat(router): add ssl support for custom domains

- README.md
- manifests/examples.yaml
- model/model.go
- nginx/config.go
This is a bundle of minor code and doc edits intended to make router a bit easier to understand on both fronts.
I've done away with the concept of "platform domain."  It's technically still there, but the old moniker didn't make much sense.  On account of the fact that the router can be used without the rest of Deis, "what platform?" might, at times, have been a relevant question.  This has been replaced with "default domain."
Similarly, I've done away with the concept of "custom domains."  _What does that even mean?_  From a deis/workflow perspective, it makes a lot of sense, but once again, from the router's perspective, loosely coupled to workflow as it is, this isn't an especially meaningful concept.
What it all boils down to, quite simply, is that for each routable service, router …
> Edit code and docs for clarity

- README.md
- model/model.go
The unnecessary verbosity of "gzipConfig" in the configuration was getting to me.  This PR exchanges it for just "gzip".
> chore(router): Make optional gzip config a little cleaner

- README.md
- model/model.go
- nginx/config.go
- router.go
Fixes #89 
~~This PR is the final bit to establish router feature parity with v1.x (minus the naxsi firewall) with v1.x.~~  This allows various SSL-related options to be fine-tuned.
Some things to note:
1.  Although this provides feature parity, defaults for some options have changed in order to earn a better grade from [Qualys SSL Labs](https://www.ssllabs.com/ssltest/analyze.html).  Just adding an appropriate cert to an app (or a wildcard cert to the platform), you can earn an A.  With some minimal tuning, an A+ is possible.
2.  There is some minor rework of things committed in #84.  The option to enforce the use of HTTPS and HSTS config options introduced there seemed like they should be pulled under the new `SSLConfig` object introduced by this PR.
3.  I intend to take a pass through …
> feat(router): Implement various ssl-related options

- README.md
- model/model.go
- model/model_validation_test.go
- nginx/config.go
- utils/modeler/errors.go
- utils/modeler/modeler.go
- utils/modeler/modeler_test.go
Fixes #96
This PR attempts to validate configuration values sourced from k8s annotations _before_ they make their way into dynamically generated Nginx configuration.
Before this PR, bad configuration values may have led to unfriendly error messages like this:
```
2016/02/02 23:59:20 [emerg] 14#0: "worker_processes" directive invalid value in /opt/nginx/conf/nginx.conf:4
nginx: [emerg] "worker_processes" directive invalid value in /opt/nginx/conf/nginx.conf:4
```
At minimum, the above requires anyone troubleshooting to `kubectl exec` to a router pod to inspect the resulting invalid Nginx configuration.  At worst, they may need to look at router code to get a better handle on what went wrong.
After this PR, however, declarative constraints (simple regular expressions) are used by the map -> …
> Config validation

- README.md
- model/model.go
- model/model_validation_test.go
- nginx/config.go
- rootfs/bin/build
Fixes #98 
Relates to #90 
This enables the Nginx VTS module to gather stats and expose them as JSON, but _only_ allows access to those stats from within the pod (I feel pretty strongly that these should not be exposed to the outside world).
cc @jchauncey: Take a look and let me know if this meets your needs.
> feat(router): Enable vts module

- README.md
- model/model.go
- model/model_validation_test.go
- utils/modeler/modeler.go
- utils/modeler/modeler_test.go
These changes complement @helgi's PR deis/workflow#338, which essentially changes the contract between workflow and router.
The change implemented here fundamentally boils down to:
__Before:__ The name of the secret bearing the certificate for any given domain was assumed to be `<domain>-cert`.
@helgi has significantly improved certificate management in workflow.
__After:__ The `router.deis.io/certificates` annotation provides a simple dictionary that maps domain names to the names of cert-bearing secrets.
> ref(router): Refactor cert management

- manifests/examples.yaml
#107 accidentally broke the examples of routable applications that are included in the manfiests dir.  This PR fixes them.
> fix(examples): Make examples routable again

- README.md
Install instructions were not updated after the need for running `helm generate <chart>` was introduced for some charts that contain templates (i.e. `deis-dev`).
This fixes that.
> doc(router): Update install instructions

- model/model.go
- nginx/config.go
Relates to #90
This improves the stats that the router exposes by grouping them by application.  Previously, they were only grouped by vhost (Nginx server block), but now they are grouped _both_ ways.
cc @slack and @jchauncey 
Here's an example of the JSON it produces.  Search for "filterZones" to see the new grouping by application.
```
{"nginxVersion":"1.9.6","loadMsec":1455133392421,"nowMsec":1455133637405,"connections":{"active":3,"reading":0,"writing":1,"waiting":2,"accepted":120,"handled":120,"requests":550},"serverZones":{"_":{"requestCounter":542,"inBytes":168677,"outBytes":415059,"responses":{"1xx":0,"2xx":542,"3xx":0,"4xx":0,"5xx":0,"miss":0,"bypass":0,"expired":0,"stale":0,"updating":0,"revalidated":0,"hit":0,"scarce":0},"overCounts":{"maxIntegerSize":18446744073709551615,"reque …
```
> feat(router): Group stats by app

- README.md
- model/model.go
- model/model_validation_test.go
- utils/modeler/modeler.go
- utils/modeler/modeler_test.go
Fixes #111 
Through changes to annotation names and documentation, this PR makes it clear what annotations configure implementation-specific options, and which must be honored by hypothetical alternative router implementations in order to ensure compatibility with deis-workflow.
> ref(router): Add impl-specific config "extensions"

- .gitignore
- Makefile
- nginx/commands.go
- nginx/config.go
- rootfs/Dockerfile
- rootfs/bin/build
- rootfs/opt/router/conf/nginx.conf
- router.go
Fixes #120 
This wasn't easy.  Running router as a non-privileged user means router can't su to start Nginx as a second unprivileged user `nginx`.  The solution is to move _everything_-- all files and processes under a new `router` user.  This works great except for a limitation that unprivileged users cannot bind to low-numbered/privileged ports like 80 and 443.  That's where `setcap` comes in.
> ref(router): Run as a non-root user

- .travis.yml
This webhook is added (or changed) such that it will kick off:
https://ci.deis.io/job/router-master
which will allow us to then better handle git information within
a connection of jobs in Jenkins to update docker version tags in
the deis helm charts and make our release process nice and smooth
> feat(.travis.yml): have this job notify its sister job in Jenkins

- nginx/config.go
- rootfs/Dockerfile
- rootfs/opt/router/sbin/boot
#120 turned out to not work nicely with Docker < 1.9.
This PR corrects that.
cc @arschles
> fix(router): Fix log permissions for non-root user

- model/model.go
> fix(ssl): Don't ever use the default/platform-wide wildcard cert for "custom" (fully qualified) domains

- .gitignore
- Makefile
```
$ docker images
REPOSITORY                     TAG       IMAGE ID       CREATED             SIZE
192.168.64.2:5000/deis/router  after     c445c3459a68   4 minutes ago       38.14 MB
192.168.64.2:5000/deis/router  before    6b62b3583f0e   11 minutes ago      64.37 MB
`
> chore(Makefile): update go-dev to 0.10.0 and compress router binary

- model/model.go
Fixes #154 
Complements https://github.com/deis/controller/pull/577
This should be merged _before_ https://github.com/deis/controller/pull/577, since this will allow both the old format and the new to work simultaneously.  After https://github.com/deis/controller/pull/577 is merged, a follow-up PR can remove the support for the old format from the router...
So yes... this change is partly temporary.
cc @helgi
> feat(certs): Add support for format of ingress TLS cert secrets

- model/model.go
- nginx/config.go
This will help when there is a custom domain. Our monitoring solution is going to use this to parse out information
The namespace is prepended to the application name only when the namespace and app name (as known by the service) are not the same. This happens with the deis namespace
Generated config:
```
set $app_name "deis/deis-workflow-manager";
set $app_name "nearby-daffodil";
```
Querying against each of those
```
[06/May/2016:04:19:54 +0000][nearby-daffodil] - 10.2.19.1 - - - 200 - "GET / HTTP/1.1" - 178 - "-" - "curl/7.43.0" - "~^nearby-daffodil\x5C.(?<domain>.+)$" - 10.3.0.107:80 - nearby-daffodil.micro-kube.io - 0.006 - 0.006
> 06/May/2016:04:20:27 +0000][deis/deis-workflow-manager] - 10.2.19.1 - - - 404 - "GET / HTTP/1.1" - 221 - "-" - "curl/7.43.0" - …
```
> feat(config): add application name as part of the log information

- model/model.go
Quite some time ago, we stopped referring to the platform domain and its cert as "default domain" or "default cert," since those have come to represent other things as the router's implementation has evolved.
This PR corrects an errant bit of text that ultimately could appear in a warning message, correcting it from "default" to "platform".
> fix(router): Improve accuracy of warning message

- README.md
- model/model.go
#158 added support for differently formatted k8s secrets conveying SSL certs. The new format was intended to match that documented for use with ingresses [here](http://kubernetes.io/docs/user-guide/ingress/#tls). #158 was tactical, however, and retained support for the old format as well. Support for the old format should be removed (as was always intended) before we go GA.
cc @helgi
> chore(ssl): Remove support for old cert secret format

- rootfs/Dockerfile
http://nginx.org/en/CHANGES-1.10
Intentionally not going for the unstable branch, until features from there are needed
> feat(*): Update nginx to 1.10.1

- nginx/config.go
This enables HTTP/2 over TLS in the DEIS Workflow router.
The config change is all that's needed, because NGINX is [already compiled with the http_v2 module](https://github.com/deis/router/blob/a8497aff73027d330abf39d27d92194ad93e61b9/rootfs/Dockerfile#L45) and ALPN support (provided by openssl 1.0.2+).
This fixes #204.
You can pull image [docker.io/felixbuenemann/router:canary](https://hub.docker.com/r/felixbuenemann/router/) for manual testing.
> Enable HTTP/2 support in the router

- model/model.go
- model/model_validation_test.go
Setting size to 0 disables checking of client request body size.
See http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
> fix(router): BodySize config can be "0"

- rootfs/Dockerfile
Fixes #221.
Note, not using 1.11.3 due to a nginx bug: https://trac.nginx.org/nginx/ticket/1032
Also bumped VTS module as it advertises compatibility. Manually verified that stats are still flowing.
> feat(*): Update nginx to 1.11.2

- .gitignore
This was missed in #224 
cc @kmala
> chore(.gitignore): Update to ignore deis-router-deployment.tmp.yaml

- Makefile
- model/model.go
- model/model_validation_test.go
- nginx/config.go
- rootfs/Dockerfile
Includes the go 1.7 toolchain: faster, smaller, better. See https://tip.golang.org/doc/go1.7.
Also updates the Docker base image to deis/base:0.3.1.
> chore(Makefile): update to go-dev 0.17.0

- rootfs/Dockerfile
This will help massively during local development as ngnix builds take a lot of time.
> ref(Dockerfile): copy the router binary after building ngnix binary

- README.md
- model/model.go
- nginx/config.go
Allow an application to enforce SSL by annotating `router.deis.io/nginx.ssl.enforce` on their service.
closes #148
TODO
> feat(router): add app SSL config

- nginx/config.go
If proxy protocol is enabled on an AWS ELB in kubernetes using the
`service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'`
annotation on the load balancer service, it will enable PROXY PROTOCOL
on all ports forwarded by the ELB, which means the builder proxy on port
2222 also needs to use `proxy_protocol` on its `listen` directive.
There is currently no way to configure PROXY PROTOCOL per port on AWS
using kubenetes service annotation and it doesn't really make sense to
enable proxy protocol only for port 80 and 443 anyways, so this fix uses
the same configuration setting as is used for http and https.
The required `proxy_protocol` option for the `listen` directive was [added in NGINX 1.11.4](https://nginx.org/en/docs/stream/ngx_stream_core_module.html#listen).
This fixes #255.
> fix(nginx): Enable builder PROXY PROTOCOL support

- router.go
> fix(nginx): known model shouldn't be refreshed if Nginx reload failed.

- model/model.go
This way we're not performing a needless API call to kubernetes.
addresses #212 slightly
> fix(model): check if CertMapping exists

- charts/router/templates/router-deployment.yaml
- charts/router/templates/router-service.yaml
- charts/router/values.yaml
fixes https://github.com/deis/charts/issues/374
This is useful if any user wants to have default annotations for all his cluster installs by using the same values file for all installs thereby not needing to do custom changes after the install.
> feat(charts): Add support to add annotations during install

- charts/router/values.yaml
This was the old default behaviour and is expected. Changing it to disabled by default is a regression. change was introduced in #296
cc @lachie83 for visibility, does this impact you in any way?
> fix(charts): enable hostports by default

- rootfs/Dockerfile
I run into errors building router locally without this change. See also deis/controller#1203 and deis/builder#475.
> fix(Dockerfile): force gunzip of license files

- charts/router/templates/router-deployment.yaml
- charts/router/values.yaml
- this allows the router to be used in a horizontal pod autoscaler out the the box. Without `resources.requests`, the HPA can't calculate a `CURRENT` value
> feat(charts): add resource requests to chart

- model/model_test.go
- nginx/config_test.go
I'm not at all sure how master got to a point where tests don't pass due to gofmt / lint issues, but that is indeed the case-- and it's going to stop other PRs I have in the pipeline from passing...
```
$ make test
docker run --rm -v /Users/kent/Code/go/src/github.com/deis/router:/go/src/github.com/deis/router -w /go/src/github.com/deis/router quay.io/deis/go-dev:v0.22.0 make style-check
lint
Manadatory Linters: These must pass
model/model_test.go:1::warning: file is not gofmted with -s (gofmt)
nginx/config_test.go:1::warning: file is not gofmted with -s (gofmt)
Optional Linters: These should pass
Makefile:94: recipe for target 'style-check' failed
make: *** [style-check] Error 1
make: *** [test-style] Error 2
```
This fixes it.
> fix(style): Apply mandatory formatting fixes

- .travis.yml
This makes travis apply style checks. It's a pretty big oversight that it isn't currently.
This also includes minor formatting fixes to `.travis.yml` itself.
Note: this will fail until #320 is merged.
> fix(.travis.yml): Make travis apply style checks

- Makefile
These two targets provide little or no value. I'd rather see them go away in the name of reducing the clutter in the Makefile.
> chore(Makefile): Remove minimally useful clean targets

- charts/router/templates/router-deployment.yaml
- charts/router/templates/router-service.yaml
I get errors trying to set `service_annotations` or `deployment_annotations` in testing #323. Templating the router service seems to be the initial problem, because the `range` loop doesn't quote the values as required.
Closes #325.
> fix(charts): quote annotation values

- charts/router/values.yaml
Host ports on some cloud providers like GKE play differently than expected.
cc @slack
> ref(charts): disable host_port/enabled by default

- charts/router/templates/router-service.yaml
Ref https://github.com/deis/router/issues/326
> feat(chart): add aws-specific idle timeout annotation to router service

- charts/router/templates/_helpers.tmpl
- charts/router/templates/router-clusterrole.yaml
- charts/router/templates/router-clusterrolebinding.yaml
- charts/router/templates/router-role.yaml
- charts/router/templates/router-rolebinding.yaml
- charts/router/values.yaml
With this change `deis-router` became available to work in **RBAC**-only clusters
Works with both Kubernetes 1.5 and 1.6 (see `templates/_helpers.tmpl` for details)
Actually tested with 1.5.7 and 1.6.2
Role allows `deis-router`:
- `extensions/deployments`: `get`
- `apps/deployments`: `get`
ClusterRole allows `deis-router`:
- `services`: `get` and `list`
- `secrets`: `get`
- `endpoints`: `get`
> RBAC support
