deis/router

nginx/commands.go, nginx/config.go, rootfs/Dockerfile, rootfs/opt/nginx/conf/nginx.conf
The PR also includes some fixes that were necessary pre-requisites to this.
=> feat(router): send nginx logs to stdout and stderr

Makefile
The alpine-based dev env is experimental, but so far seems to work nicely with the router.  Let's roll with it for now.
Ping @helgi @technosophos
=> chore(Makefile): switch to alpine-based dev environment

.travis.yml, Makefile, _scripts/deploy.sh
Requesting reviews from @helgi and @mboersma
=> feat(ci): integrate with travis

README.md, manifests/deis-router-rc.yaml, manifests/examples.yaml, model/model.go
=> chore(router): prefix annotations with deis.com/

manifests/examples.yaml
=> chore(manifests): improve formatting

nginx/config.go
These are minor format fixes for improved consistency.
=> chore(router): fix format

README.md, model/model.go, nginx/config.go
Another PR on the march to v1.x feature parity.  ~~WIP, because rebase and doc updates are needed after #27~~
=> feat(router): add support for keepalive_timeout

nginx/config.go
Another incremental change to increase consistency with the old router.
=> chore(router): set server_name_in_redirect and port_in_redirect off

model/model.go, nginx/config.go
=> fix(router): drop error-prone check for services w/o endpoints

README.md, model/model.go, nginx/config.go
Fixes #50 
This also changes units for all timeouts to seconds for consistency.
=> feat(router): make timeouts configurable at app level

README.md, model/model.go, nginx/config.go
=> feat(router): honor application ip/cidr whitelists

manifests/deis-router-rc.yaml
=> feat(manifests): Add liveness and readiness probes

README.md
This corrects a crucial inaccuracy in the docs.
=> doc(router): Fix doc about routable label

README.md, model/model.go, nginx/config.go
=> fix(router): Make gzip disableable again

README.md, model/model.go, nginx/config.go
Added these two features together since they're pretty intertwined.
=> feat(router): Add support for forcing HTTPS and using HSTS

nginx/config.go
Fixes #99 
Port relevant subset of fixes forward from deis/deis#4877
=> fix(router): Fix issues establishing real end-client IP

nginx/config.go
This was accidentally hard-coded before.  This fixes that.
=> feat(router): Make default vhost ssl protocols configurable

README.md, model/model.go
Fixes #105 
cc @helgi: this works fine as it turns out.
=> ref(router): Add namespace to the routable label

README.md
=> doc(router): Document LB idle connection timeout

README.md
=> doc(router): Add generic instructions for manual LB setup

.travis.yml, Makefile, includes.mk
=> chore(ci): Always run docker build during CI

manifests/deis-router-rc.yaml, nginx/config.go, rootfs/Dockerfile
Fixes #125 
Strategic alternative to #126 
cc @arschles
=> fix(router): Only use unprivileged ports

README.md
=> doc(certs): Fix flaw in domain:cert association doc

README.md
=> doc(router): Add production considerations

Makefile, glide.lock
=> chore(build/test): Upgrade to latest dev environment

Makefile, _scripts/deploy.sh, versioning.mk
=> chore(Makefile): Enable immutable (git-based) Docker tag publishing

README.md
Ref deis/deis#4962
cc/ @krancour @mboersma @slack
=> doc(README.md): update the readme to reflect beta status

model/model.go, nginx/config.go
Fixes #150 
Relates to deis/workflow-e2e#122
Necessitates the following change in [workflow-e2e](https://github.com/deis/workflow-e2e):
=> feat(router): Respond with 503 for upstream svcs w/ no endpoints

nginx/config.go
=> fix(router): Allow for comma-delimited X-Forwarded-Proto

nginx/config.go
=> feat(config): move from time_local to time_iso8601

README.md
These are minor doc updates that mainly address name changes among related products-- notably that "Deis v2" is now "Deis Workflow" (should have addressed this a while ago) and that the original "Helm" is now "Helm Classic" (with its binary also renamed from `helm` to `helmc`).
=> docs(README): Apply minor updates

CHANGELOG.md
=> doc(CHANGELOG.md): add entry for v2.0.0-rc1

nginx/config.go
=> feat(router): Pass on X-Forwarded-Proto and X-Forwarded-Port

nginx/config.go
=> fix(router): Fix app_name issue

nginx/config.go
Closes #144 
In addition to what #144 called for, this does the same for any custom dhparam that may have been used-- deletes it if it is no longer used.
=> feat(ssl): Delete unused certs and dhparam

README.md
As well as update latest stable version to `workflow-rc2`
Ref https://github.com/deis/workflow/issues/285
=> chore(README.md): remove beta status

README.md
=> doc(readme): Add anchors to every row in annotations table

README.md
=> docs(README): fix Go report card badge

model/model.go, model/model_validation_test.go
Adjust constraints in AppConfig/RouterConfig
See deis/controller#851
=> feat(IDN): add support for international domains

README.md
=> docs(readme): Clarify that routable services must expose port 80

model/model.go, model/model_validation_test.go
Closes #227 
cc @felixbuenemann
=> fix(model): Improve regex for SSL ciphers

model/model.go
fixes #233 
cc @bacongobbler @krancour
=> fix(routable): Use correct label key for routable

rootfs/Dockerfile
See https://github.com/deis/docker-base/releases/tag/v0.3.2
=> chore(Dockerfile): bump deis/base to v0.3.2

nginx/config.go
=> fix(ngnix): handle X-Forwarded-Port and X-Forwarded-Proto properly

charts/router/templates/router-deployment.yaml
ref https://github.com/deis/charts/pull/368
=> fix(charts): bump router's livenessProbe initial delay

rootfs/Dockerfile
See https://nginx.org/en/CHANGES
=> chore(nginx): update nginx to 1.11.6

rootfs/Dockerfile
See https://nginx.org/en/CHANGES
=> chore(nginx): update nginx to 1.11.7

rootfs/Dockerfile
See https://nginx.org/en/CHANGES
=> chore(nginx): update nginx to 1.11.8

charts/router/values.yaml
closes https://github.com/deis/workflow/issues/689
=> fix(charts): remove deployment and service annotations

rootfs/Dockerfile
See https://nginx.org/en/CHANGES
=> chore(nginx): update nginx to 1.11.9

Makefile
See https://github.com/deis/docker-go-dev/releases/tag/v0.22.0
=> chore(Makefile): update docker-go-dev to v0.22.0

rootfs/Dockerfile
See http://nginx.org/en/CHANGES. Mostly bugfixes since 1.11.10.
=> chore(Dockerfile): update nginx to 1.11.13

rootfs/Dockerfile
See http://nginx.org/en/CHANGES-1.12
=> chore(Dockerfile): update nginx to 1.12.0 stable

rootfs/Dockerfile
=> chore(Dockerfile): update nginx to 1.13.0

rootfs/Dockerfile
Changes with nginx 1.13.3                                        11 Jul 2017
*) Security: a specially crafted request might result in an integer
overflow and incorrect processing of ranges in the range filter,
potentially resulting in sensitive information leak (CVE-2017-7529).
=> chore(Dockerfile): update nginx to 1.13.3

rootfs/Dockerfile
See http://nginx.org/en/CHANGES
=> chore(Dockerfile): update nginx to 1.13.4
